<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25641" started-at="2015-10-08T15:09:19Z" finished-at="2015-10-08T15:09:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25641" started-at="2015-10-08T15:09:19Z" finished-at="2015-10-08T15:09:45Z">
      <class name="com.portal.Simulador">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.portal.Simulador@17c68925]" name="setUp" is-config="true" duration-ms="4983" started-at="2015-10-08T10:09:19Z" finished-at="2015-10-08T10:09:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testSimulacion1()[pri:0, instance:com.portal.Simulador@17c68925]" name="testSimulacion1" duration-ms="20037" started-at="2015-10-08T10:09:24Z" finished-at="2015-10-08T10:09:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<$100.000+> but was:<>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<$100.000+> but was:<>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at com.portal.Simulador.testSimulacion1(Simulador.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSimulacion1 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.portal.Simulador@17c68925]" name="tearDown" is-config="true" duration-ms="591" started-at="2015-10-08T10:09:44Z" finished-at="2015-10-08T10:09:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.portal.Simulador -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
